### PR TITLE
Fix database credentials for development

### LINKED ISSUE #10: Setting up project not working
I'm following the setup instructions, when running `mix ecto.create` I get this error. Any ideas?
```
❯ mix ecto.create
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.2) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.2) lib/supervisor.ex:556: Supervisor.start_link/2
  (stdlib 3.12) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.12) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.12) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.12) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.12) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.12) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.12) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.2) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.2) lib/supervisor.ex:556: Supervisor.start_link/2
  (stdlib 3.12) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.12) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.12) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.12) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.12) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.12) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.12) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3


21:07:11.384 [error] GenServer #PID<0.237.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.0.3) lib/db_connection/connection.ex:84: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Xrt.Repo couldn't be created: killed
```

### PR DESCRIPTION
**Pull request by uesteibar**
Fixes https://github.com/retro-tool/retro-tool/issues/10

I also took advantage of this PR to update the elixir version to the latest (1.10).

### CODE REVIEW

File: config/dev.exs [hunk 1]
```diff
@@ -61,7 +61,7 @@ config :phoenix, :plug_init_mode, :runtime
 # Configure your database
 config :retro, Xrt.Repo,
   username: System.get_env("DB_USER") || "postgres",
-  password: System.get_env("DB_PASSWORD") || "",
+  password: System.get_env("DB_PASSWORD") || "password",
```
Comment (atrzaska) [inline config/dev.exs]: default password is postgres

File: config/test.exs [hunk 2]
```diff
@@ -12,7 +12,7 @@ config :logger, level: :warn
 # Configure your database
 config :retro, Xrt.Repo,
   username: "postgres",
-  password: "",
+  password: "password",
```
Comment (atrzaska) [inline config/test.exs]: can you set default to postgres?

File: config/dev.exs (hunk 1 above)
Comment (uesteibar) [reply config/dev.exs]: last minute changes gone wrong 😅 changed!

**Review by atrzaska — APPROVED** [review]
